In [2]:
import numpy as np
np.__version__

'2.3.2'

Creatig a List

In [3]:
list = [1,2,3,4,5,6,7,8]
type(list)

list

# creating aList

In [4]:
arr = np.array(list)
type(arr)

numpy.ndarray

In [5]:
# Arrange Function

In [6]:
np.arange(12)   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.arange(20,50,5)   #print 20 to 50 by step 5 \\ start-end-step

array([20, 25, 30, 35, 40, 45])

In [8]:
np.arange(20,10)

array([], dtype=int64)

In [9]:
np.arange(-20,10)    #the frist element is always biggest

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

# Zeros Function

In [10]:
np.zeros(2)    #by default it gives float data type

array([0., 0.])

In [11]:
np.zeros(3 , dtype=int)       #one dimentionalarray

array([0, 0, 0])

In [12]:
np.zeros((2,4),dtype = int)     #this is two-d-array , 2 is for row and 4 is columns

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones((9,9),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

# Reshape a array

In [14]:
np.arange(1,13).reshape(3,4)    #converted 3 rows and 4 column

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Random Function

In [15]:
np.random.random((1,5))          #genrate random no. 1 to 5

array([[0.03656318, 0.57871904, 0.60071745, 0.49983036, 0.47742302]])

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.random.rand(2,6)           #bu default gives float values

array([[0.47742183, 0.54716955, 0.7007349 , 0.78114446, 0.7610952 ,
        0.82978333],
       [0.29637576, 0.68708989, 0.93758615, 0.92880129, 0.42839816,
        0.48128525]])

In [18]:
np.random.randint(2,6,4)             #it gives integer values 2 to 6 ,4 is size

array([4, 3, 2, 5], dtype=int32)

In [19]:
np.random.randint(10,50 ,(10,5))    #10*5 matrix

array([[26, 25, 47, 40, 29],
       [39, 27, 19, 28, 47],
       [42, 47, 32, 10, 47],
       [41, 34, 43, 20, 16],
       [16, 28, 48, 46, 46],
       [24, 14, 26, 10, 11],
       [41, 10, 32, 49, 20],
       [13, 21, 10, 36, 26],
       [28, 42, 31, 23, 49],
       [16, 23, 28, 39, 28]], dtype=int32)

In [20]:
# reshape the lsit
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# indexing and sclicing in matrix

In [21]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 15, 11, 17],
       [16, 19, 15, 10],
       [12, 18, 11, 15],
       [19, 14, 18, 11],
       [17, 10, 13, 19]], dtype=int32)

In [22]:
b[1:3]

array([[16, 19, 15, 10],
       [12, 18, 11, 15]], dtype=int32)

In [23]:
b[1:4]

array([[16, 19, 15, 10],
       [12, 18, 11, 15],
       [19, 14, 18, 11]], dtype=int32)

when you use (,) it print the only one element based on row and column ,the (2,4) the 2 is row and 4 is column 

In [24]:
b[1,-1]

np.int32(10)

In [25]:
b[2,3]       #the 2 is row and 3 is column

np.int32(15)

In [26]:
b[2:5]       #(:) colun is used for slicing

array([[12, 18, 11, 15],
       [19, 14, 18, 11],
       [17, 10, 13, 19]], dtype=int32)

In [27]:
b[-5,-3]    #commma(,) is used for get element

np.int32(15)

In [28]:
b[-3,-3]

np.int32(18)

In [29]:
b[2,1]          

np.int32(18)

In [30]:
b[-2,-3]

np.int32(14)

In [31]:
b[2:4]

array([[12, 18, 11, 15],
       [19, 14, 18, 11]], dtype=int32)

In [32]:
b[2:5]

array([[12, 18, 11, 15],
       [19, 14, 18, 11],
       [17, 10, 13, 19]], dtype=int32)

In [33]:
b[-4:4]

array([[16, 19, 15, 10],
       [12, 18, 11, 15],
       [19, 14, 18, 11]], dtype=int32)

In [34]:
b[-5:3]    

array([[18, 15, 11, 17],
       [16, 19, 15, 10],
       [12, 18, 11, 15]], dtype=int32)

Operations


In [35]:
arr = np.random.randint(0,100,(10,10))
arr

array([[44, 90, 52, 15, 96, 89, 29, 48, 87, 86],
       [23, 63, 60, 69,  6, 96, 51, 16, 68, 26],
       [54, 19, 37, 87, 77, 64, 99,  4, 36, 17],
       [26, 62, 49, 58, 25, 51, 51,  9, 83, 69],
       [95, 47, 55, 43, 22, 15, 68, 11, 75, 50],
       [96, 76, 23,  6,  0, 82,  0, 59, 33, 30],
       [ 2, 39, 36,  2, 66,  9, 61, 21, 93, 65],
       [40, 82, 42, 60, 50, 24, 71, 62, 81, 65],
       [62, 19, 69, 31, 83, 98, 54, 62, 24, 10],
       [26,  5, 34, 46, 85, 70, 70, 78, 22, 56]], dtype=int32)

In [36]:
arr[-5:-1]    

array([[96, 76, 23,  6,  0, 82,  0, 59, 33, 30],
       [ 2, 39, 36,  2, 66,  9, 61, 21, 93, 65],
       [40, 82, 42, 60, 50, 24, 71, 62, 81, 65],
       [62, 19, 69, 31, 83, 98, 54, 62, 24, 10]], dtype=int32)

In [37]:
arr[5,5]

np.int32(82)

In [38]:
arr[4,3]

np.int32(43)

In [39]:
arr[-2,-2]

np.int32(24)

In [40]:
arr[::2]

array([[44, 90, 52, 15, 96, 89, 29, 48, 87, 86],
       [54, 19, 37, 87, 77, 64, 99,  4, 36, 17],
       [95, 47, 55, 43, 22, 15, 68, 11, 75, 50],
       [ 2, 39, 36,  2, 66,  9, 61, 21, 93, 65],
       [62, 19, 69, 31, 83, 98, 54, 62, 24, 10]], dtype=int32)

MAX ,MEAN ,MEDIAN ,MODE

In [41]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [42]:
max(a)

np.int64(5)

In [43]:
a.mean()

np.float64(2.5)

In [44]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
a.reshape(2,3)           #2*3=6

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
mat = np.random.randint(0,100,(10,10))
mat

array([[89, 61, 56, 82, 95, 22, 96, 98, 94, 69],
       [88, 44,  4, 72, 36, 31, 41, 32, 68, 57],
       [72, 12, 38, 81, 65, 93, 14, 33, 47, 28],
       [ 2, 10, 77, 23,  0, 15, 97, 22, 81, 90],
       [ 6, 10, 85, 51, 18, 73, 83, 63, 79, 27],
       [23, 97, 32, 42, 23, 71, 26, 65, 99, 60],
       [11, 76, 42, 54, 18, 95, 58, 76, 64, 78],
       [ 8, 55, 39, 82, 97,  3, 45, 28,  8, 42],
       [47,  1, 80, 48,  4, 85, 12, 86, 29, 61],
       [40,  3, 45, 70, 28, 82, 66, 22, 55, 54]], dtype=int32)

In [47]:
row = 4
col = 5

In [48]:
mat[row,col]

np.int32(73)

In [49]:
mat[7]       #print the index 7 row

array([ 8, 55, 39, 82, 97,  3, 45, 28,  8, 42], dtype=int32)

In [50]:
mat[7,4]

np.int32(97)

In [51]:
mat[2:4]

array([[72, 12, 38, 81, 65, 93, 14, 33, 47, 28],
       [ 2, 10, 77, 23,  0, 15, 97, 22, 81, 90]], dtype=int32)

In [52]:
mat[2:4,2:4]                #row 2 to 4 and column 2 to 4

array([[38, 81],
       [77, 23]], dtype=int32)

In [53]:
 mat[3:5,3:5]

array([[23,  0],
       [51, 18]], dtype=int32)

In [54]:
mat[:8]

array([[89, 61, 56, 82, 95, 22, 96, 98, 94, 69],
       [88, 44,  4, 72, 36, 31, 41, 32, 68, 57],
       [72, 12, 38, 81, 65, 93, 14, 33, 47, 28],
       [ 2, 10, 77, 23,  0, 15, 97, 22, 81, 90],
       [ 6, 10, 85, 51, 18, 73, 83, 63, 79, 27],
       [23, 97, 32, 42, 23, 71, 26, 65, 99, 60],
       [11, 76, 42, 54, 18, 95, 58, 76, 64, 78],
       [ 8, 55, 39, 82, 97,  3, 45, 28,  8, 42]], dtype=int32)

In [55]:
mat[:,8]        #print 8 no. column

array([94, 68, 47, 81, 79, 99, 64,  8, 29, 55], dtype=int32)

In [56]:
mat[3:-3]         

array([[ 2, 10, 77, 23,  0, 15, 97, 22, 81, 90],
       [ 6, 10, 85, 51, 18, 73, 83, 63, 79, 27],
       [23, 97, 32, 42, 23, 71, 26, 65, 99, 60],
       [11, 76, 42, 54, 18, 95, 58, 76, 64, 78]], dtype=int32)

In [59]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a = np.random.randint(1,100,(10,10))
a

array([[14, 36, 52, 29, 29,  2, 27, 96, 31,  8],
       [83, 55,  4, 32, 13,  5, 67, 75, 56, 59],
       [ 1,  5, 99, 35, 31, 31, 26, 19,  7, 99],
       [13, 15, 19, 23, 70, 62, 60, 43, 29, 29],
       [64, 26, 54, 92,  8, 90, 39, 94, 79, 59],
       [22, 82, 72, 44,  2, 63,  2, 89, 41, 94],
       [89,  4, 77, 18, 28, 11, 79, 64, 58, 72],
       [63, 10, 57, 77, 90, 26, 76,  8, 42, 20],
       [84, 24, 63, 92, 11, 65,  5, 12, 30, 52],
       [92, 15, 15, 84, 75, 11, 96, 16, 56, 67]], dtype=int32)

In [61]:
a[0:5]

array([[14, 36, 52, 29, 29,  2, 27, 96, 31,  8],
       [83, 55,  4, 32, 13,  5, 67, 75, 56, 59],
       [ 1,  5, 99, 35, 31, 31, 26, 19,  7, 99],
       [13, 15, 19, 23, 70, 62, 60, 43, 29, 29],
       [64, 26, 54, 92,  8, 90, 39, 94, 79, 59]], dtype=int32)

In [62]:
a[2,2]

np.int32(99)

In [63]:
a[3]

array([13, 15, 19, 23, 70, 62, 60, 43, 29, 29], dtype=int32)

In [64]:
a[4,0]

np.int32(64)

In [65]:
a[-9,-2]

np.int32(56)

In [66]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
b.min()

np.int64(1)